name: deploy-container # workflow name

on:
  push:
    branches:
      - main
    paths:
      - "packages/container/**"

defaults:
  run:
    working-directory: packages/container

jobs:
  build: # will make one single job to build and then deploy the app
    runs-on: ubuntu-latest # the virtual machine created by Github
    steps: # the actual commands to be executed
      - uses: actions/checkout@v2 # checkout the code from our project, so take it inside of our repo and load it into the virtual machine
      - run: npm install # installing dependencies into our project
      - run: npm run build # run webpack build process, then generate the dist directory
      # after we build the project, we want to deploy all these built files off to Amazon S3, using AWS CLI that gives us programmatic access to Amazon Web Services
      - uses: chrislennon/actions-aws-cli@v1.1 # getting access to the AWS CLI
      - run: aws s3 sync dist s3://${{secrets.AWS_S3_BUCKET_NAME}}/container/latest # use CLI to run a command, sync the contents of the dist directory which is the output from the build step with an S3 bucket (a place we can store files on AWS)
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
